    print(" 1 : perimeterRectangle")
        print(" 2 : areaRectangle")
        print(" 3 : diagonalRectangle")
        print(" 4 : perimeterCircle")
        print(" 5 : areaCircle")
        print(" 6 : perimeterSquare")
        print(" 7 : areaSquare")
        print(" 8 : diagonalSquare")
        print(" 9 : diagonalParallelepiped")
        print(" 10 : areaTriangle")
        print(" 11: areaRhombus")
        option = int(input("Choose an option below:. Choose 0 to exit. "))